apiVersion: apps/v1
kind: Deployment
metadata:
  name: javdep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javdep
  template:
    metadata:
      name: javpod
      labels:
        app: javdep
    spec:
      containers:
      - name: c1
        image: cazzzzz/java-app:1.0
        envFrom:
        - configMapRef:
            name: 2tierconfig
        - secretRef:
            name: 2tiersecret
 
        ports:
        - containerPort: 8080