apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod
  labels:
    app: mysqlpod
spec:
  containers:
    - name: mysqlcontainer
      image: cazzzzz/mysqlimage:1.0
      ports: 
        - containerPort: 3306